name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  flutter-test:
    name: Flutter Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test

      - name: Test Build (Debug APK)
        run: flutter build apk --debug
